name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dry-deployment:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up JDK 21
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Upload, Close and Drop
        run: ./gradlew uploadJavaOSSRHToMavenCentralNexus close drop
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

  release-and-delivery:
    needs: dry-deployment
    permissions: # Not specified scopes are set to `none`!
      packages: write
      contents: write
    concurrency:
      group: release-and-delivery-${{ github.event.number || github.ref }}
    runs-on: ubuntu-24.04
    outputs:
      release-status: ${{ env.release_status }} # see release.config.js
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true
      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT
      - name: Install Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
